user: auto

ssh:
  port: 22222
  allow_root: false
  password_auth: false

firewall:
  enabled: true
  tailscale_only: true
  allow_lan_ssh: false

tailscale:
  required: true
  enable_ssh: false

extras:
  homebrew: true
  dokploy: false
  zsh: true
  ohmyzsh: true
  starship: true
  yazi: true
  node: false
  codex: true
  claudecode: true
  kimi: false
  camoufox: false
  cargo: true
  pm2: true
  pnpm: true
  tcs: true
  tsx: true
  openclaw: true
  clawvault: false
  bun: true
  whisper: false
  rbw: false
  llamacpp: true
  herdr: true
  dotfiles: true

dokploy:
  version: latest

openclaw:
  version: latest
